name = "vstar"
# This tells Pages which directory contains your static assets (dist, build, out, etc.)
pages_build_output_dir = ".vercel/output/static" 
compatibility_date = "2024-03-07"
compatibility_flags = ["nodejs_compat"]